image: node:20

stages:
  - install
  - test
  - build

cache:
  paths:
    - node_modules/

install_dependencies:
  stage: install
  script:
    - npm install
  only:
    - master

run_tests:
  stage: test
  script:
    - npm test
  artifacts:
    paths:
      - coverage/
  only:
    - master

build_app:
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - build/
  only:
    - master